### ISSUE TITLE
What about backups?

### ISSUE THREAD

**Issue by dolmen** [mpiorowski/sgsg#12]
The deployment section of the README lacks information about how to enable backups.

What about integrating [litestream](https://github.com/benbjohnson/litestream) or another SQLite backup solution?

**Comment by mpiorowski** [comment]
Very good idea, the way i do it is a simpel as possible, got a cron running that every night just run `sqlite3 db.sqlite3 ".backup db.back"`  and scp that sends it into my home server :)

Will add this into Readme description. And will also suggest Your solution, which i didnt know before.

**Comment by mpiorowski** [comment]
Added a script and section i nReadme :)
